name: play_bold
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dotted_decoration: ^2.0.0
  equatable: ^2.0.7
  flutter_bloc: ^9.1.0
  get_it: ^8.0.3
  go_router: ^14.8.1
  rive: ^0.13.20
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
